spring:
  mail:
    host: smtp.qq.com # 配置 QQ 邮箱服务器地址
    port: 587 # 端口
    username: xx@qq.com # QQ 邮箱账号
    password: xx # QQ 邮箱的授权码
    default-encoding: UTF-8 # 配置默认编码
    properties:
      mail:
        smtp:
          auth: true  # 是否需要认证
          starttls:
            enable: true  # 是否启用 SSL/TLS 安全连接